// frontend_vue/src/App.vue
<template>
  <el-container class="app-container">
    <!-- 顶部导航 -->
    <el-header class="app-header">
      <div class="header-left">
        <h1 class="app-title">QwenImg AI 创作平台</h1>
        <el-tag type="info" size="small">阿里云通义万相</el-tag>
      </div>
      <div class="header-right">
        <el-button type="primary" :icon="Github" link @click="openGithub">
          GitHub
        </el-button>
      </div>
    </el-header>

    <el-container>
      <!-- 左侧菜单 -->
      <el-aside width="200px" class="app-aside">
        <el-menu :default-active="activeMenu" @select="handleMenuSelect">
          <el-menu-item-group title="创作工具">
            <el-menu-item index="text_to_image">
              <el-icon><Picture /></el-icon>
              <span>文生图</span>
            </el-menu-item>
            <el-menu-item index="image_to_video">
              <el-icon><VideoCamera /></el-icon>
              <span>图生视频</span>
            </el-menu-item>
            <el-menu-item index="text_to_video">
              <el-icon><Film /></el-icon>
              <span>文生视频</span>
            </el-menu-item>
          </el-menu-item-group>
          <el-menu-item-group title="管理">
            <el-menu-item index="history">
              <el-icon><Clock /></el-icon>
              <span>历史记录</span>
            </el-menu-item>
          </el-menu-item-group>
        </el-menu>
      </el-aside>

      <!-- 主内容区 -->
      <el-container>
        <el-main class="app-main">
          <el-row :gutter="24">
            <!-- 左侧主区域 -->
            <el-col :xs="24" :lg="16">
              <component :is="currentComponent" />
            </el-col>

            <!-- 右侧任务面板 -->
            <el-col :xs="24" :lg="8">
              <ActiveTasks />
            </el-col>
          </el-row>
        </el-main>
      </el-container>
    </el-container>
  </el-container>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { Picture, VideoCamera, Film, Clock, Github } from '@element-plus/icons-vue'
import { useAppStore } from './stores/app'
import TextToImage from './components/TextToImage.vue'
import ImageToVideo from './components/ImageToVideo.vue'
import TextToVideo from './components/TextToVideo.vue'
import History from './components/History.vue'
import ActiveTasks from './components/ActiveTasks.vue'

const store = useAppStore()
const activeMenu = ref('text_to_image')

const components: Record<string, any> = {
  text_to_image: TextToImage,
  image_to_video: ImageToVideo,
  text_to_video: TextToVideo,
  history: History,
}

const currentComponent = computed(() => components[activeMenu.value])

function handleMenuSelect(index: string) {
  activeMenu.value = index
}

function openGithub() {
  window.open('https://github.com/cclank/qwenimg', '_blank')
}

onMounted(() => {
  store.connectWebSocket()
})

onUnmounted(() => {
  store.disconnectWebSocket()
})
</script>

<style scoped>
.app-container {
  height: 100vh;
}

.app-header {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
  color: white;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 16px;
}

.app-title {
  margin: 0;
  font-size: 20px;
  font-weight: 600;
}

.app-aside {
  background: #fff;
  border-right: 1px solid #e0e0e0;
}

.app-main {
  background: #f5f7fa;
  padding: 24px;
}
</style>

// frontend/src/App.tsx
/**
 * 主应用组件
 */
import React, { useState, useEffect } from 'react';
import {
  Layout,
  Menu,
  Typography,
  Space,
  Button,
  Modal,
  Input,
  message,
  Row,
  Col,
} from 'antd';
import {
  PictureOutlined,
  VideoCameraOutlined,
  PlayCircleOutlined,
  HistoryOutlined,
  BulbOutlined,
  SettingOutlined,
  GithubOutlined,
} from '@ant-design/icons';
import { TextToImage } from './components/TextToImage';
import { ImageToVideo } from './components/ImageToVideo';
import { TextToVideo } from './components/TextToVideo';
import { History } from './components/History';
import { Inspiration } from './components/Inspiration';
import { ActiveTasksPanel } from './components/ActiveTasksPanel';
import { useWebSocket } from './hooks/useWebSocket';
import { useAppStore } from './store';
import './App.css';

const { Header, Content, Sider } = Layout;
const { Title, Text } = Typography;

function App() {
  const [activeKey, setActiveKey] = useState('text_to_image');
  const [settingsVisible, setSettingsVisible] = useState(false);
  const [collapsed, setCollapsed] = useState(false);
  const apiKey = useAppStore((state) => state.apiKey);
  const setApiKey = useAppStore((state) => state.setApiKey);
  const sessionId = useAppStore((state) => state.sessionId);
  const addTask = useAppStore((state) => state.addTask);

  // 初始化WebSocket
  useWebSocket();

  // 页面加载时获取历史任务
  useEffect(() => {
    const fetchHistoryTasks = async () => {
      try {
        const response = await fetch(`/api/generation/tasks?session_id=${sessionId}&page_size=20`);
        if (response.ok) {
          const data = await response.json();
          // 将历史任务添加到状态中（避免重复添加）
          data.tasks.forEach((task: any) => {
            // 检查任务是否已存在
            // 注意：这里简化处理，实际应该检查任务ID是否已存在
            addTask({
              task_id: task.task_id,
              task_type: task.task_type,
              status: task.status,
              progress: task.progress,
              prompt: task.prompt,
              result_urls: task.result_urls,
              error_message: task.error_message,
              created_at: task.created_at,
              completed_at: task.completed_at,
            });
          });
        }
      } catch (error) {
        console.error('Failed to fetch history tasks:', error);
      }
    };

    fetchHistoryTasks();
  }, [sessionId, addTask]);

  const handleSaveSettings = (key: string) => {
    setApiKey(key);
    setSettingsVisible(false);
    message.success('设置已保存');
  };

  const renderContent = () => {
    switch (activeKey) {
      case 'text_to_image':
        return <TextToImage />;
      case 'image_to_video':
        return <ImageToVideo />;
      case 'text_to_video':
        return <TextToVideo />;
      case 'history':
        return <History />;
      case 'inspiration':
        return <Inspiration />;
      default:
        return <TextToImage />;
    }
  };

  return (
    <Layout style={{ minHeight: '100vh' }}>
      {/* 顶部导航 */}
      <Header
        style={{
          background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          padding: '0 24px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
        }}
      >
        <Space size="large">
          <Title
            level={3}
            style={{
              margin: 0,
              color: '#fff',
              fontWeight: 'bold',
              letterSpacing: 1,
            }}
          >
            QwenImg AI 创作平台
          </Title>
          <Text style={{ color: 'rgba(255,255,255,0.8)', fontSize: 12 }}>
            阿里云通义万相多模态AI
          </Text>
        </Space>

        <Space>
          <Button
            type="text"
            icon={<SettingOutlined />}
            onClick={() => setSettingsVisible(true)}
            style={{ color: '#fff' }}
          >
            设置
          </Button>
          <Button
            type="text"
            icon={<GithubOutlined />}
            href="https://github.com/cclank/qwenimg"
            target="_blank"
            style={{ color: '#fff' }}
          >
            GitHub
          </Button>
        </Space>
      </Header>

      <Layout>
        {/* 左侧菜单 */}
        <Sider
          collapsible
          collapsed={collapsed}
          onCollapse={setCollapsed}
          width={200}
          style={{ background: '#fff' }}
        >
          <Menu
            mode="inline"
            selectedKeys={[activeKey]}
            onClick={({ key }) => setActiveKey(key)}
            style={{ height: '100%', borderRight: 0 }}
            items={[
              {
                key: 'generation',
                label: '创作工具',
                type: 'group',
                children: [
                  {
                    key: 'text_to_image',
                    icon: <PictureOutlined />,
                    label: '文生图',
                  },
                  {
                    key: 'image_to_video',
                    icon: <VideoCameraOutlined />,
                    label: '图生视频',
                  },
                  {
                    key: 'text_to_video',
                    icon: <PlayCircleOutlined />,
                    label: '文生视频',
                  },
                ],
              },
              {
                key: 'manage',
                label: '管理',
                type: 'group',
                children: [
                  {
                    key: 'history',
                    icon: <HistoryOutlined />,
                    label: '历史记录',
                  },
                  {
                    key: 'inspiration',
                    icon: <BulbOutlined />,
                    label: '灵感画廊',
                  },
                ],
              },
            ]}
          />
        </Sider>

        {/* 主内容区 */}
        <Layout style={{ padding: '24px' }}>
          <Content>
            <Row gutter={24}>
              {/* 左侧主区域 */}
              <Col xs={24} xl={16}>
                {renderContent()}
              </Col>

              {/* 右侧任务面板 */}
              <Col xs={24} xl={8}>
                <ActiveTasksPanel />
              </Col>
            </Row>
          </Content>
        </Layout>
      </Layout>

      {/* 设置对话框 */}
      <Modal
        title="设置"
        open={settingsVisible}
        onCancel={() => setSettingsVisible(false)}
        footer={null}
      >
        <Space direction="vertical" style={{ width: '100%' }}>
          <div>
            <Text strong>DashScope API Key</Text>
            <Input.Password
              placeholder="请输入你的API Key"
              defaultValue={apiKey}
              onPressEnter={(e) =>
                handleSaveSettings((e.target as HTMLInputElement).value)
              }
              style={{ marginTop: 8 }}
            />
            <Text type="secondary" style={{ fontSize: 12 }}>
              从{' '}
              <a
                href="https://dashscope.console.aliyun.com/apiKey"
                target="_blank"
                rel="noreferrer"
              >
                阿里云控制台
              </a>{' '}
              获取
            </Text>
          </div>

          <div>
            <Text strong>会话ID</Text>
            <Input value={sessionId} disabled style={{ marginTop: 8 }} />
            <Text type="secondary" style={{ fontSize: 12 }}>
              用于WebSocket实时通信
            </Text>
          </div>

          <Button
            type="primary"
            onClick={() => {
              const input = document.querySelector(
                'input[type="password"]'
              ) as HTMLInputElement;
              if (input) {
                handleSaveSettings(input.value);
              }
            }}
            block
          >
            保存设置
          </Button>
        </Space>
      </Modal>
    </Layout>
  );
}

export default App;
