// frontend/src/components/ImageToVideo.tsx
/**
 * 图生视频组件
 */
import React, { useState } from 'react';
import {
  Form,
  Input,
  Button,
  Select,
  InputNumber,
  Switch,
  Space,
  Card,
  Row,
  Col,
  Upload,
  message,
} from 'antd';
import {
  ThunderboltOutlined,
  VideoCameraOutlined,
  UploadOutlined,
} from '@ant-design/icons';
import type { UploadFile } from 'antd/es/upload/interface';
import { generationAPI } from '@/services/api';
import { useAppStore } from '@/store';
import type { ImageToVideoRequest } from '@/types';

const { TextArea } = Input;
const { Option } = Select;

export const ImageToVideo: React.FC = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);
  const [imageUrl, setImageUrl] = useState<string>('');
  const sessionId = useAppStore((state) => state.sessionId);
  const addTask = useAppStore((state) => state.addTask);

  const handleUpload = (file: File) => {
    // 转换为Base64
    const reader = new FileReader();
    reader.onload = () => {
      const base64 = reader.result as string;
      setImageUrl(base64);
      form.setFieldValue('image_url', base64);
    };
    reader.readAsDataURL(file);
    return false; // 阻止自动上传
  };

  const handleSubmit = async (values: any) => {
    if (!imageUrl) {
      message.error('请先上传图片');
      return;
    }

    try {
      setLoading(true);
      console.log('Submitting image to video task with session_id:', sessionId);

      const request: ImageToVideoRequest = {
        ...values,
        image_url: imageUrl,
        session_id: sessionId,
      };

      const response = await generationAPI.imageToVideo(request);
      console.log('Task created successfully:', response);

      addTask({
        task_id: response.task_id,
        task_type: 'image_to_video',
        status: 'pending',
        progress: 0,
        prompt: values.prompt || '图生视频',
      });

      message.success('任务已创建，正在生成中...');
    } catch (error: any) {
      console.error('Failed to create task:', error);
      message.error(error.response?.data?.detail || '创建任务失败');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card
      title={
        <Space>
          <VideoCameraOutlined />
          <span>图生视频</span>
        </Space>
      }
      bordered={false}
    >
      <Form
        form={form}
        layout="vertical"
        onFinish={handleSubmit}
        initialValues={{
          model: 'wan2.5-i2v-preview',
          resolution: '1080P',
          duration: 10,
          watermark: false,
        }}
      >
        <Row gutter={16}>
          <Col xs={24} lg={12}>
            <Form.Item
              label="上传图片"
              name="image_upload"
              rules={[{ required: !imageUrl, message: '请上传图片' }]}
            >
              <Upload
                accept="image/*"
                beforeUpload={handleUpload}
                maxCount={1}
                listType="picture-card"
              >
                <div>
                  <UploadOutlined />
                  <div style={{ marginTop: 8 }}>上传图片</div>
                </div>
              </Upload>
            </Form.Item>
            <Form.Item name="image_url" hidden>
              <Input />
            </Form.Item>
          </Col>

          <Col xs={24} lg={12}>
            <Form.Item label="动作描述（可选）" name="prompt">
              <TextArea
                rows={4}
                placeholder="描述视频中的动作，例如：摄像机缓慢推进，阳光从左侧照射"
                showCount
                maxLength={500}
              />
            </Form.Item>
          </Col>
        </Row>

        <Row gutter={16}>
          <Col xs={24} lg={12}>
            <Form.Item label="负面提示词" name="negative_prompt">
              <TextArea
                rows={3}
                placeholder="描述你不想要的元素"
                showCount
                maxLength={500}
              />
            </Form.Item>
          </Col>

          <Col xs={24} lg={12}>
            <Row gutter={16}>
              <Col xs={24} sm={12}>
                <Form.Item label="分辨率" name="resolution">
                  <Select>
                    <Option value="480P">480P</Option>
                    <Option value="720P">720P</Option>
                    <Option value="1080P">1080P</Option>
                  </Select>
                </Form.Item>
              </Col>

              <Col xs={24} sm={12}>
                <Form.Item label="时长" name="duration">
                  <Select>
                    <Option value={5}>5秒</Option>
                    <Option value={10}>10秒</Option>
                  </Select>
                </Form.Item>
              </Col>
            </Row>

            <Form.Item label="随机种子" name="seed">
              <InputNumber
                min={0}
                max={4294967290}
                style={{ width: '100%' }}
                placeholder="可选"
              />
            </Form.Item>
          </Col>
        </Row>

        <Row gutter={16}>
          <Col xs={24} sm={12}>
            <Form.Item label="添加水印" name="watermark" valuePropName="checked">
              <Switch />
            </Form.Item>
          </Col>
        </Row>

        <Form.Item>
          <Button
            type="primary"
            htmlType="submit"
            loading={loading}
            icon={<ThunderboltOutlined />}
            size="large"
            block
          >
            {loading ? '创建中...' : '开始生成'}
          </Button>
        </Form.Item>
      </Form>
    </Card>
  );
};

// frontend_vue/src/components/ImageToVideo.vue
<template>
  <el-card shadow="hover">
    <template #header>
      <div class="card-header">
        <span>图生视频</span>
        <el-tag>Image to Video</el-tag>
      </div>
    </template>

    <el-form :model="form" label-width="100px">
      <el-form-item label="上传图片">
        <el-upload
          class="upload-demo"
          drag
          :auto-upload="false"
          :on-change="handleFileChange"
          :limit="1"
          accept="image/*"
        >
          <el-icon class="el-icon--upload"><Upload /></el-icon>
          <div class="el-upload__text">
            拖拽文件到此处或 <em>点击上传</em>
          </div>
        </el-upload>
      </el-form-item>

      <el-form-item label="图片预览" v-if="imagePreview">
        <img :src="imagePreview" alt="预览" style="max-width: 300px" />
      </el-form-item>

      <el-form-item>
        <el-button
          type="primary"
          :loading="loading"
          :disabled="!imageFile"
          @click="handleSubmit"
        >
          开始生成
        </el-button>
        <el-button @click="handleReset">重置</el-button>
      </el-form-item>
    </el-form>
  </el-card>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { ElMessage } from 'element-plus'
import { Upload } from '@element-plus/icons-vue'
import { taskApi } from '../api'
import { useAppStore } from '../stores/app'
import type { UploadFile } from 'element-plus'

const store = useAppStore()
const loading = ref(false)
const imageFile = ref<File | null>(null)
const imagePreview = ref('')

const form = reactive({})

function handleFileChange(file: UploadFile) {
  if (file.raw) {
    imageFile.value = file.raw
    // 创建预览
    const reader = new FileReader()
    reader.onload = (e) => {
      imagePreview.value = e.target?.result as string
    }
    reader.readAsDataURL(file.raw)
  }
}

async function handleSubmit() {
  if (!imageFile.value) {
    ElMessage.warning('请先上传图片')
    return
  }

  loading.value = true
  try {
    // 转换为 base64
    const reader = new FileReader()
    reader.onload = async (e) => {
      const base64 = e.target?.result as string
      const response = await taskApi.createTask(
        'image_to_video',
        { image_data: base64 },
        store.sessionId
      )
      ElMessage.success('任务已创建，正在生成中...')

      store.addTask({
        task_id: response.data.task_id,
        task_type: 'image_to_video',
        status: 'pending',
        created_at: new Date().toISOString(),
        params: {},
      })
      loading.value = false
    }
    reader.readAsDataURL(imageFile.value)
  } catch (error: any) {
    ElMessage.error(error.response?.data?.detail || '创建任务失败')
    loading.value = false
  }
}

function handleReset() {
  imageFile.value = null
  imagePreview.value = ''
}
</script>

<style scoped>
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
